# Copyright (c) 2024 Smart Rollerz e.V. All rights reserved.

model_path: "models/epochs-50_batch_size-16_learning_rate-0.01.tflite"
# model_path: "models/smartrollerz_train_short_edgetpu.tflite"
labels_path: "models/labels.txt"
detection_size: [640, 640]
