# Copyright (c) 2024 Smart Rollerz e.V. All rights reserved.

object_detection_node:
  ros__parameters:
    debug: False
    image_subscriber: "/camera/image/undistorted"
    object_publisher: "/object_detection/object"
    sign_publisher: "/object_detection/sign"
    debug_img_publisher: "/object_detection/debug/image"
    state: 0 # 0: inactive, 1: active
    dt: 0.0002
    config_path: "config/model.yaml"
